{% set version = "2.0.0" %}

package:
  name: openalea.components
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python multisetup.py install


requirements:
  build:
    - openalea.deploy
    - openalea.misc
  run:
    - openalea.deploy
    - openalea.misc
    - openalea.core
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - openalea.math

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License