name: OpenAlea CI

on:
  push:
    paths:
      - 'numpy/**'
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'numpy/**'
    types:
      - opened
      - synchronize
      - reopened
  release:
    types:
      - published

jobs:
  build:
    uses: openalea/action-build-publish-anaconda/.github/workflows/openalea_ci.yml@main
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}

    with:
      conda-directory: numpy/conda
      python-minor-version: "[10, 11, 12]"
      operating-system: '[ "ubuntu-latest" , "macos-13" , "windows-latest"]'
